# 개발 도구
brew "git"
brew "pnpm"
brew "wget"
brew "tree"
brew "gh"
brew "cloc"
brew "duti"
brew "mas"

# 앱
cask "cloudflare-warp"
cask "google-chrome"
cask "claude-code"
cask "visual-studio-code"
cask "iterm2"
cask "fork"
cask "dropbox"
cask "1password"
cask "vlc"
cask "figma"
cask "slack"
cask "telegram"

# Mac App Store
mas "Moom Classic", id: 419330170

# 폰트
cask "font-source-code-pro"
